Include ImportLibs and other missing attributes
leibnitz27/olewoo pull request #1
Opened 2018-05-05 14:32 UTC by bclothier

The PR attempts to make the IDL file generated by olewoo be compilable by MIDL by including the required `ImportLib` attributes and additionally include any `custom` attributes and `version` attribute to achieve closer parity with what is outputted by default oleview.exe.

The dependent libraries are pulled in using the code provided in this [Stack Overflow thread](https://stackoverflow.com/questions/45063037/find-dependent-type-libraries-in-typelib-file-through-code). It was also necessary to perform some registry lookup to supplement the data that is not given via the `ITypeLib` alone. Running the IDL through MIDL can give compilation error if the `ImportLib` is not on the path, so for that reason, olewoo will now supply the full path to the dependent libraries to aid the MIDL compilation. 

We also make use of `ITypeLib2` / `ITypeInfo2` to extract any custom data which should be included to ensure parity when generating type libraries from the provided IDL.

2018-05-28 23:18 UTC, leibnitz27 reviewed
should hive and libkey be (using)?

2018-05-28 23:20 UTC, leibnitz27 commented on olewoo_cs/Typelib/OWCustData.cs
> +            t2.GetAllFuncCustData(index, ptr);
As discussed in mail - this currently causes an exception - pls patch in your other changes?
With the separate patch you sent me, I get an exception rendering scrrun.dll

2018-05-28 23:33 UTC, leibnitz27 approved these changes

2018-05-28 23:34 UTC, leibnitz27 requested changes
Fix needed for fatal issues in getAllFuncCustData

2018-06-30 13:00 UTC, bclothier commented
Closing this in lieu of a PR that address the issues identified.

2018-06-30 13:00 UTC, closed without merging